# Generated by Django 3.2.4 on 2022-03-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='no_eggs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flan',
            name='no_lactose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flan',
            name='no_sugar',
            field=models.BooleanField(default=False),
        ),
    ]
