# Generated by Django 3.2.4 on 2022-03-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220324_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
